theme: jekyll-theme-minimal
logo: https://d1u82yn7miridg.cloudfront.net/eyJidWNrZXQiOiJsYWJyb290cy1hc3NldHMiLCJrZXkiOiJfcHVibGljXC9fZmlsZXNcL3N5c3RlbVwvY2tcL3RyZW5kaW5nXC8xODk3MTFfd2ViXzYyZjA3ZWRmMDc5YmJlMjk1NjQ3NTgxMWU0OTg3OTdiLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NzAwLCJmaXQiOiJjb3ZlciJ9fX0=
title: Joseph's Bioinformatics Class (BGGN 213, Winter 2020)
